#!/usr/bin/env node
//
// Post-build step. Create React App emits one index.html and Vercel serves it
// for every route, so before JavaScript runs, /menu and /about carried the
// homepage's title, description and, worst of all, the homepage's canonical URL.
// Every public URL therefore declared itself to be the homepage. That is the
// signal behind "Duplicate, Google chose a different canonical", and it is why
// only a couple of pages were getting indexed.
//
// This writes a real HTML file per route with that route's own head tags, so a
// crawler landing on /menu sees /menu's canonical whether or not it executes
// JavaScript. The body is still rendered by React: only the head differs, which
// is the part that decides indexing and share previews.
//
// sitemap.xml is generated from the same list, so the two can never drift.

const fs = require('fs');
const path = require('path');
const { ROUTES, OG_IMAGE, canonicalFor } = require('../seo-routes');

const BUILD_DIR = path.resolve(__dirname, '..', 'build');
const INDEX = path.join(BUILD_DIR, 'index.html');

function fail(message) {
  console.error(`\n[seo-build] ${message}\n`);
  process.exit(1);
}

// Escape for use in an HTML attribute value or text node. Titles contain "&".
function esc(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Replace a single tag matched by `pattern`. Throws when the tag is missing or
// ambiguous rather than returning the HTML unchanged: a silent no-op here would
// mean shipping wrong canonicals, which is the exact failure this script exists
// to prevent.
function replaceOne(html, pattern, replacement, label) {
  const matches = html.match(new RegExp(pattern.source, pattern.flags.replace('g', '') + 'g'));
  if (!matches || matches.length === 0) {
    fail(`could not find ${label} in build/index.html. Has public/index.html changed?`);
  }
  if (matches.length > 1) {
    fail(`found ${matches.length} copies of ${label} in build/index.html, expected exactly one.`);
  }
  return html.replace(pattern, replacement);
}

function headFor(template, route) {
  const canonical = canonicalFor(route.path);
  const title = esc(route.title);
  const description = esc(route.description);

  let html = template;
  html = replaceOne(html, /<title>[\s\S]*?<\/title>/, `<title>${title}</title>`, '<title>');
  html = replaceOne(
    html,
    /<meta name="description"[^>]*>/,
    `<meta name="description" content="${description}"/>`,
    'meta description'
  );
  html = replaceOne(
    html,
    /<meta property="og:title"[^>]*>/,
    `<meta property="og:title" content="${title}"/>`,
    'og:title'
  );
  html = replaceOne(
    html,
    /<meta property="og:description"[^>]*>/,
    `<meta property="og:description" content="${description}"/>`,
    'og:description'
  );
  html = replaceOne(
    html,
    /<meta property="og:url"[^>]*>/,
    `<meta property="og:url" content="${canonical}"/>`,
    'og:url'
  );
  html = replaceOne(
    html,
    /<meta property="og:image"[^>]*>/,
    `<meta property="og:image" content="${OG_IMAGE}"/>`,
    'og:image'
  );
  html = replaceOne(
    html,
    /<meta name="twitter:title"[^>]*>/,
    `<meta name="twitter:title" content="${title}"/>`,
    'twitter:title'
  );
  html = replaceOne(
    html,
    /<meta name="twitter:description"[^>]*>/,
    `<meta name="twitter:description" content="${description}"/>`,
    'twitter:description'
  );
  html = replaceOne(
    html,
    /<link rel="canonical"[^>]*>/,
    `<link rel="canonical" href="${canonical}"/>`,
    'rel=canonical'
  );
  return html;
}

function writeSitemap() {
  const body = ROUTES.map((r) => `  <url>\n    <loc>${canonicalFor(r.path)}</loc>\n  </url>`).join('\n');
  const xml =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<!--\n' +
    '  Generated by scripts/seo-build.js from seo-routes.js. Do not edit by hand.\n' +
    '  No changefreq or priority: we do not know how often these change and search\n' +
    '  engines do not need us guessing.\n' +
    '-->\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    `${body}\n` +
    '</urlset>\n';
  fs.writeFileSync(path.join(BUILD_DIR, 'sitemap.xml'), xml);
  return ROUTES.length;
}

function main() {
  if (!fs.existsSync(INDEX)) {
    fail('build/index.html not found. Run this after react-scripts build.');
  }
  const template = fs.readFileSync(INDEX, 'utf8');

  ROUTES.forEach((route) => {
    const html = headFor(template, route);
    if (route.path === '/') {
      fs.writeFileSync(INDEX, html);
    } else {
      // Directory form, so Vercel's filesystem handler serves /menu from
      // menu/index.html before the SPA catch-all rewrite is reached. If it ever
      // does not, the catch-all still returns the app, so a miss degrades to
      // today's behaviour rather than a 404.
      const dir = path.join(BUILD_DIR, route.path.replace(/^\/+/, ''));
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'index.html'), html);
    }
    console.log(`[seo-build] ${route.path.padEnd(14)} -> ${canonicalFor(route.path)}`);
  });

  const count = writeSitemap();
  console.log(`[seo-build] sitemap.xml written with ${count} URLs`);
}

main();
